// Auto-generated CAN Message IDs
#ifndef CAN_MSG_IDS_H
#define CAN_MSG_IDS_H

typedef enum {
    MSG_DEBUG_2_0                            = 0x000,
    MSG_DEBUG_FD                             = 0x001,
    MSG_PING                                 = 0x002,
    MSG_ECU_STATUS_1                         = 0x003,
    MSG_ECU_STATUS_2                         = 0x004,
    MSG_ECU_STATUS_3                         = 0x005,
    MSG_ECU_CONFIG                           = 0x006,
    MSG_ACU_STATUS_1                         = 0x007,
    MSG_ACU_STATUS_2                         = 0x008,
    MSG_ACU_STATUS_3                         = 0x009,
    MSG_ACU_PRECHARGE                        = 0x00A,
    MSG_ACU_CONFIG_CHARGE_PARAMETERS         = 0x00B,
    MSG_ACU_CONFIG_OPERATIONAL_PARAMETERS    = 0x00C,
    MSG_ACU_CELL_DATA_1                      = 0x00D,
    MSG_ACU_CELL_DATA_2                      = 0x00E,
    MSG_ACU_CELL_DATA_3                      = 0x00F,
    MSG_ACU_CELL_DATA_4                      = 0x010,
    MSG_ACU_CELL_DATA_5                      = 0x011,
    MSG_INVERTER_STATUS_1                    = 0x013,
    MSG_INVERTER_STATUS_2                    = 0x014,
    MSG_INVERTER_STATUS_3                    = 0x015,
    MSG_INVERTER_CONFIG                      = 0x016,
    MSG_INVERTER_COMMAND                     = 0x017,
    MSG_FAN_STATUS                           = 0x018,
    MSG_FAN_COMMAND                          = 0x019,
    MSG_DASH_STATUS                          = 0x01A,
    MSG_DASH_CONFIG                          = 0x01B,
    MSG_STEERING_STATUS                      = 0x01C,
    MSG_STEERING_CONFIG                      = 0x01D,
    MSG_SAM_BRAKE_IR                         = 0x01E,
    MSG_SAM_TIRE_TEMP                        = 0x01F,
    MSG_SAM_IMU                              = 0x020,
    MSG_SAM_GPS_1                            = 0x021,
    MSG_SAM_GPS_2                            = 0x022,
    MSG_SAM_GPS_TIME                         = 0x023,
    MSG_SAM_GPS_HEADING                      = 0x024,
    MSG_SAM_SUS_POTS                         = 0x025,
    MSG_SAM_TOF                              = 0x026,
    MSG_SAM_REAR_WHEELSPEED                  = 0x027,
    MSG_SAM_PUSHROD_FORCE                    = 0x028,
    MSG_TCM_STATUS                           = 0x029,
    MSG_TCM_RESOURCE_UTILIZATION             = 0x02A,
    MSG_DASH_WARNING_FLAGS                   = 0x02B,
    MSG_SPECIFIC_BRAKE_IR                    = 0x02C,
    MSG_ECU_PING_INFORMATION                 = 0x02D,
    MSG_ECU_PEDALS_DATA                      = 0x02E,
    MSG_GPS_LAT                              = 0x031,
    MSG_GPS_LON                              = 0x032,
    MSG_GPS_ALT                              = 0x033,
    MSG_GPS_PX                               = 0x034,
    MSG_GPS_QY                               = 0x035,
    MSG_GPS_RZ                               = 0x036,
    MSG_UVW_DGPS                             = 0x030,
} can_msg_id_t;

#endif // CAN_MSG_IDS_H
