// Auto-generated CAN Message IDs
#ifndef CAN_MSG_IDS_H
#define CAN_MSG_IDS_H

typedef enum {
    MSG_ACU_CELL_DATA_1_CAN_ID               = 0x00D,
    MSG_ACU_CELL_DATA_2_CAN_ID               = 0x00E,
    MSG_ACU_CELL_DATA_3_CAN_ID               = 0x00F,
    MSG_ACU_CELL_DATA_4_CAN_ID               = 0x010,
    MSG_ACU_CELL_DATA_5_CAN_ID               = 0x011,
    MSG_ACU_CONFIG_CHARGE_PARAMETERS_CAN_ID  = 0x00B,
    MSG_ACU_CONFIG_OPERATIONAL_PARAMETERS_CAN_ID = 0x00C,
    MSG_ACU_PRECHARGE_CAN_ID                 = 0x00A,
    MSG_ACU_STATUS_1_CAN_ID                  = 0x007,
    MSG_ACU_STATUS_2_CAN_ID                  = 0x008,
    MSG_ACU_STATUS_3_CAN_ID                  = 0x009,
    MSG_DASH_CONFIG_CAN_ID                   = 0x01B,
    MSG_DASH_STATUS_CAN_ID                   = 0x01A,
    MSG_DASH_WARNING_FLAGS_CAN_ID            = 0x02B,
    MSG_DEBUG_2_0_CAN_ID                     = 0x000,
    MSG_DEBUG_FD_CAN_ID                      = 0x001,
    MSG_ECU_CONFIG_CAN_ID                    = 0x006,
    MSG_ECU_PEDALS_DATA_CAN_ID               = 0x02E,
    MSG_ECU_PING_INFORMATION_CAN_ID          = 0x02D,
    MSG_ECU_STATUS_1_CAN_ID                  = 0x003,
    MSG_ECU_STATUS_2_CAN_ID                  = 0x004,
    MSG_ECU_STATUS_3_CAN_ID                  = 0x005,
    MSG_FAN_COMMAND_CAN_ID                   = 0x019,
    MSG_FAN_STATUS_CAN_ID                    = 0x018,
    MSG_GPS_ALT_CAN_ID                       = 0x033,
    MSG_GPS_LAT_CAN_ID                       = 0x031,
    MSG_GPS_LON_CAN_ID                       = 0x032,
    MSG_GPS_PX_CAN_ID                        = 0x034,
    MSG_GPS_QY_CAN_ID                        = 0x035,
    MSG_GPS_RZ_CAN_ID                        = 0x036,
    MSG_INVERTER_COMMAND_CAN_ID              = 0x017,
    MSG_INVERTER_CONFIG_CAN_ID               = 0x016,
    MSG_INVERTER_STATUS_1_CAN_ID             = 0x013,
    MSG_INVERTER_STATUS_2_CAN_ID             = 0x014,
    MSG_INVERTER_STATUS_3_CAN_ID             = 0x015,
    MSG_PING_CAN_ID                          = 0x002,
    MSG_SAM_BRAKE_IR_CAN_ID                  = 0x01E,
    MSG_SAM_GPS_1_CAN_ID                     = 0x021,
    MSG_SAM_GPS_2_CAN_ID                     = 0x022,
    MSG_SAM_GPS_HEADING_CAN_ID               = 0x024,
    MSG_SAM_GPS_TIME_CAN_ID                  = 0x023,
    MSG_SAM_IMU_CAN_ID                       = 0x020,
    MSG_SAM_PUSHROD_FORCE_CAN_ID             = 0x028,
    MSG_SAM_REAR_WHEELSPEED_CAN_ID           = 0x027,
    MSG_SAM_SUS_POTS_CAN_ID                  = 0x025,
    MSG_SAM_TIRE_TEMP_CAN_ID                 = 0x01F,
    MSG_SAM_TOF_CAN_ID                       = 0x026,
    MSG_SPECIFIC_BRAKE_IR_CAN_ID             = 0x02C,
    MSG_STEERING_CONFIG_CAN_ID               = 0x01D,
    MSG_STEERING_STATUS_CAN_ID               = 0x01C,
    MSG_TCM_RESOURCE_UTILIZATION_CAN_ID      = 0x02A,
    MSG_TCM_STATUS_CAN_ID                    = 0x029,
    MSG_UVW_DGPS_CAN_ID                      = 0x030,
} GRCAN_MSG_ID_t;

#endif // CAN_MSG_IDS_H
