// Auto-generated GR ID enum header
#ifndef GR_IDS_H
#define GR_IDS_H

typedef enum {
	GRCAN_ALL = 0x00,
	GRCAN_Charger = 0x00,
	GRCAN_DTI_Inverter = 0x00,
	GRCAN_Energy_Meter = 0x00,
	GRCAN_IMD = 0x00,
	GRCAN_Debugger = 0x01,
	GRCAN_CCU = 0x02,
	GRCAN_ECU = 0x02,
	GRCAN_BCU = 0x03,
	GRCAN_TCM = 0x04,
	GRCAN_Dash_Panel = 0x05,
	GRCAN_GR_Inverter = 0x08,
	GRCAN_Charging_SDC = 0x0C,
	GRCAN_Fan_Controller_1 = 0x0D,
	GRCAN_Fan_Controller_2 = 0x0E,
	GRCAN_Fan_Controller_3 = 0x0F,
	GRCAN_InboardFloor_FL = 0x20,
	GRCAN_InboardFloor_FR = 0x21,
	GRCAN_InboardFloor_RL = 0x22,
	GRCAN_InboardFloor_RR = 0x23,
	GRCAN_SuspensionNode_FL = 0x24,
	GRCAN_SuspensionNode_FR = 0x25,
	GRCAN_SuspensionNode_RL = 0x26,
	GRCAN_SuspensionNode_RR = 0x27,
	GRCAN_TireTemp_FL = 0x28,
	GRCAN_TireTemp_FR = 0x29,
	GRCAN_TireTemp_RL = 0x2A,
	GRCAN_TireTemp_RR = 0x2B,
	GRCAN_DGPS = 0x30,
	GRCAN_TireTemp_FL = 0x10,
	GRCAN_TireTemp_FR = 0x11,
	GRCAN_TireTemp_RL = 0x12,
	GRCAN_TireTemp_RR = 0x13,
	GRCAN_Suspension_FL = 0x14,
	GRCAN_Suspension_FR = 0x15,
	GRCAN_Suspension_RL = 0x16,
	GRCAN_Suspension_RR = 0x17,
	GRCAN_InboardFloor_FL = 0x18,
	GRCAN_InboardFloor_FR = 0x19,
	GRCAN_InboardFloor_RL = 0x1A,
	GRCAN_InboardFloor_RR = 0x1B,
	GRCAN_BrakeTemp_FL = 0x1C,
	GRCAN_BrakeTemp_FR = 0x1D,
	GRCAN_BrakeTemp_RL = 0x1E,
	GRCAN_BrakeTemp_RR = 0x1F,
	GRCAN_DGPS = 0x20,
} GRCAN_NODE_ID;

#endif // GR_IDS_H
