// Auto-generated Custom CAN ID header
#ifndef CUSTOM_CAN_ID_H
#define CUSTOM_CAN_ID_H

typedef enum {
    CHARGER_CONTROL_CAN_ID = 0x1806e5f4,
    CHARGER_DATA_CAN_ID = 0x18ff50e5,
    DTI_CONTROL_1_CAN_ID = 116,
    DTI_CONTROL_10_CAN_ID = 0xa16,
    DTI_CONTROL_11_CAN_ID = 0xb16,
    DTI_CONTROL_12_CAN_ID = 0xc16,
    DTI_CONTROL_2_CAN_ID = 216,
    DTI_CONTROL_3_CAN_ID = 316,
    DTI_CONTROL_4_CAN_ID = 416,
    DTI_CONTROL_5_CAN_ID = 516,
    DTI_CONTROL_6_CAN_ID = 616,
    DTI_CONTROL_7_CAN_ID = 716,
    DTI_CONTROL_8_CAN_ID = 816,
    DTI_CONTROL_9_CAN_ID = 916,
    DTI_DATA_1_CAN_ID = 2016,
    DTI_DATA_2_CAN_ID = 2116,
    DTI_DATA_3_CAN_ID = 2216,
    DTI_DATA_4_CAN_ID = 2316,
    DTI_DATA_5_CAN_ID = 2416,
    EM_MEASUREMENT_CAN_ID = 0x10,
    EM_STATUS_CAN_ID = 0x40,
    EM_TEAM_DATA_1_CAN_ID = 0x30,
    EM_TEAM_DATA_2_CAN_ID = 0x30e,
    EM_TEMPERATURE_CAN_ID = 0x60,
    IMD_IT_SYSTEM_CAN_ID = 0x18eff4fe,
    IMD_GENERAL_CAN_ID = 0x18ff01f4,
    IMD_ISOLATION_INFO_CAN_ID = 0x18eff4fe,
    IMD_REQUEST_CAN_ID = 0x18eff4fe,
    IMD_RESPONSE_CAN_ID = 23,
    IMD_VOLTAGE_CAN_ID = 0x18eff4fe,
} Custom_CAN_ID_t;

// Signals for Charger Control
typedef enum {
    CHARGER_CONTROL_SET_VOLTAGE_START = 0,
    CHARGER_CONTROL_SET_VOLTAGE_LEN   = 1,
    CHARGER_CONTROL_SET_CURRENT_START = 16,
    CHARGER_CONTROL_SET_CURRENT_LEN   = 1,
    CHARGER_CONTROL_CHARGE_ENABLE_START = 17,
    CHARGER_CONTROL_CHARGE_ENABLE_LEN   = 1,
} CHARGER_CONTROL_SIGNALS_t;

// Signals for Charger Data
typedef enum {
    CHARGER_DATA_OUTPUT_VOLTAGE_START = 0,
    CHARGER_DATA_OUTPUT_VOLTAGE_LEN   = 1,
    CHARGER_DATA_OUTPUT_CURRENT_START = 16,
    CHARGER_DATA_OUTPUT_CURRENT_LEN   = 1,
    CHARGER_DATA_HARDWARE_FAILURE_START = 17,
    CHARGER_DATA_HARDWARE_FAILURE_LEN   = 1,
    CHARGER_DATA_OVERTEMP_START = 18,
    CHARGER_DATA_OVERTEMP_LEN   = 1,
    CHARGER_DATA_INPUT_VOLTAGE_ERROR_START = 19,
    CHARGER_DATA_INPUT_VOLTAGE_ERROR_LEN   = 1,
    CHARGER_DATA_CONNECTION_ERROR_START = 20,
    CHARGER_DATA_CONNECTION_ERROR_LEN   = 1,
    CHARGER_DATA_COMMUNICATION_STATE_START = 21,
    CHARGER_DATA_COMMUNICATION_STATE_LEN   = 1,
    CHARGER_DATA_RESERVED_START = 24,
    CHARGER_DATA_RESERVED_LEN   = 1,
} CHARGER_DATA_SIGNALS_t;

// Signals for DTI Control 1
typedef enum {
    DTI_CONTROL_1_TARGET_AC_CURRENT_START = 0,
    DTI_CONTROL_1_TARGET_AC_CURRENT_LEN   = 1,
} DTI_CONTROL_1_SIGNALS_t;

// Signals for DTI Control 10
typedef enum {
    DTI_CONTROL_10_MAX_DC_CURRENT_START = 0,
    DTI_CONTROL_10_MAX_DC_CURRENT_LEN   = 1,
} DTI_CONTROL_10_SIGNALS_t;

// Signals for DTI Control 11
typedef enum {
    DTI_CONTROL_11_MAX_BRAKE_DC_CURRENT_START = 0,
    DTI_CONTROL_11_MAX_BRAKE_DC_CURRENT_LEN   = 1,
} DTI_CONTROL_11_SIGNALS_t;

// Signals for DTI Control 12
typedef enum {
    DTI_CONTROL_12_DRIVE_ENABLE_START = 0,
    DTI_CONTROL_12_DRIVE_ENABLE_LEN   = 1,
} DTI_CONTROL_12_SIGNALS_t;

// Signals for DTI Control 2
typedef enum {
    DTI_CONTROL_2_TARGET_BRAKE_CURRENT_START = 0,
    DTI_CONTROL_2_TARGET_BRAKE_CURRENT_LEN   = 1,
} DTI_CONTROL_2_SIGNALS_t;

// Signals for DTI Control 3
typedef enum {
    DTI_CONTROL_3_TARGET_ERPM_START = 0,
    DTI_CONTROL_3_TARGET_ERPM_LEN   = 1,
} DTI_CONTROL_3_SIGNALS_t;

// Signals for DTI Control 4
typedef enum {
    DTI_CONTROL_4_TARGET_POSITION_START = 0,
    DTI_CONTROL_4_TARGET_POSITION_LEN   = 1,
} DTI_CONTROL_4_SIGNALS_t;

// Signals for DTI Control 5
typedef enum {
    DTI_CONTROL_5_R_AC_CURRENT_START = 0,
    DTI_CONTROL_5_R_AC_CURRENT_LEN   = 1,
} DTI_CONTROL_5_SIGNALS_t;

// Signals for DTI Control 6
typedef enum {
    DTI_CONTROL_6_R_AC_BRAKE_CURRENT_START = 0,
    DTI_CONTROL_6_R_AC_BRAKE_CURRENT_LEN   = 1,
} DTI_CONTROL_6_SIGNALS_t;

// Signals for DTI Control 7
typedef enum {
    DTI_CONTROL_7_DIGITAL_OUTPUT_1_START = 0,
    DTI_CONTROL_7_DIGITAL_OUTPUT_1_LEN   = 1,
    DTI_CONTROL_7_DIGITAL_OUTPUT_2_START = 1,
    DTI_CONTROL_7_DIGITAL_OUTPUT_2_LEN   = 1,
    DTI_CONTROL_7_DIGITAL_OUTPUT_3_START = 2,
    DTI_CONTROL_7_DIGITAL_OUTPUT_3_LEN   = 1,
    DTI_CONTROL_7_DIGITAL_OUTPUT_4_START = 3,
    DTI_CONTROL_7_DIGITAL_OUTPUT_4_LEN   = 1,
} DTI_CONTROL_7_SIGNALS_t;

// Signals for DTI Control 8
typedef enum {
    DTI_CONTROL_8_MAX_AC_CURRENT_START = 0,
    DTI_CONTROL_8_MAX_AC_CURRENT_LEN   = 1,
} DTI_CONTROL_8_SIGNALS_t;

// Signals for DTI Control 9
typedef enum {
    DTI_CONTROL_9_MAX_BRAKE_AC_CURRENT_START = 0,
    DTI_CONTROL_9_MAX_BRAKE_AC_CURRENT_LEN   = 1,
} DTI_CONTROL_9_SIGNALS_t;

// Signals for DTI Data 1
typedef enum {
    DTI_DATA_1_ERPM_START = 0,
    DTI_DATA_1_ERPM_LEN   = 1,
    DTI_DATA_1_DUTY_CYCLE_START = 32,
    DTI_DATA_1_DUTY_CYCLE_LEN   = 1,
    DTI_DATA_1_INPUT_VOLTAGE_START = 48,
    DTI_DATA_1_INPUT_VOLTAGE_LEN   = 1,
} DTI_DATA_1_SIGNALS_t;

// Signals for DTI Data 2
typedef enum {
    DTI_DATA_2_AC_CURRENT_START = 0,
    DTI_DATA_2_AC_CURRENT_LEN   = 1,
    DTI_DATA_2_DC_CURRENT_START = 16,
    DTI_DATA_2_DC_CURRENT_LEN   = 1,
    DTI_DATA_2_RESERVED_START = 32,
    DTI_DATA_2_RESERVED_LEN   = 1,
} DTI_DATA_2_SIGNALS_t;

// Signals for DTI Data 3
typedef enum {
    DTI_DATA_3_CONTROLLER_TEMP_START = 0,
    DTI_DATA_3_CONTROLLER_TEMP_LEN   = 1,
    DTI_DATA_3_MOTOR_TEMP_START = 16,
    DTI_DATA_3_MOTOR_TEMP_LEN   = 1,
    DTI_DATA_3_FAULT_CODES_START = 32,
    DTI_DATA_3_FAULT_CODES_LEN   = 1,
    DTI_DATA_3_RESERVED_START = 40,
    DTI_DATA_3_RESERVED_LEN   = 1,
} DTI_DATA_3_SIGNALS_t;

// Signals for DTI Data 4
typedef enum {
    DTI_DATA_4_FOC_ID_START = 0,
    DTI_DATA_4_FOC_ID_LEN   = 1,
    DTI_DATA_4_FOC_IQ_START = 32,
    DTI_DATA_4_FOC_IQ_LEN   = 1,
} DTI_DATA_4_SIGNALS_t;

// Signals for DTI Data 5
typedef enum {
    DTI_DATA_5_THROTTLE_START = 0,
    DTI_DATA_5_THROTTLE_LEN   = 1,
    DTI_DATA_5_BRAKE_START = 8,
    DTI_DATA_5_BRAKE_LEN   = 1,
    DTI_DATA_5_DIGITAL_INPUT_1_START = 16,
    DTI_DATA_5_DIGITAL_INPUT_1_LEN   = 1,
    DTI_DATA_5_DIGITAL_INPUT_2_START = 17,
    DTI_DATA_5_DIGITAL_INPUT_2_LEN   = 1,
    DTI_DATA_5_DIGITAL_INPUT_3_START = 18,
    DTI_DATA_5_DIGITAL_INPUT_3_LEN   = 1,
    DTI_DATA_5_DIGITAL_INPUT_4_START = 19,
    DTI_DATA_5_DIGITAL_INPUT_4_LEN   = 1,
    DTI_DATA_5_DIGITAL_OUTPUT_1_START = 20,
    DTI_DATA_5_DIGITAL_OUTPUT_1_LEN   = 1,
    DTI_DATA_5_DIGITAL_OUTPUT_2_START = 21,
    DTI_DATA_5_DIGITAL_OUTPUT_2_LEN   = 1,
    DTI_DATA_5_DIGITAL_OUTPUT_3_START = 22,
    DTI_DATA_5_DIGITAL_OUTPUT_3_LEN   = 1,
    DTI_DATA_5_DIGITAL_OUTPUT_4_START = 23,
    DTI_DATA_5_DIGITAL_OUTPUT_4_LEN   = 1,
    DTI_DATA_5_DRIVE_ENABLE_START = 24,
    DTI_DATA_5_DRIVE_ENABLE_LEN   = 1,
    DTI_DATA_5_CAPACITOR_TEMP_LIMIT_START = 32,
    DTI_DATA_5_CAPACITOR_TEMP_LIMIT_LEN   = 1,
    DTI_DATA_5_DC_CURRENT_LIMIT_START = 33,
    DTI_DATA_5_DC_CURRENT_LIMIT_LEN   = 1,
    DTI_DATA_5_DRIVE_ENABLE_LIMIT_START = 34,
    DTI_DATA_5_DRIVE_ENABLE_LIMIT_LEN   = 1,
    DTI_DATA_5_IGBT_ACCELERATION_TEMPERATURE_LIMIT_START = 35,
    DTI_DATA_5_IGBT_ACCELERATION_TEMPERATURE_LIMIT_LEN   = 1,
    DTI_DATA_5_IGBT_TEMPERATURE_LIMIT_START = 36,
    DTI_DATA_5_IGBT_TEMPERATURE_LIMIT_LEN   = 1,
    DTI_DATA_5_INPUT_VOLTAGE_LIMIT_START = 37,
    DTI_DATA_5_INPUT_VOLTAGE_LIMIT_LEN   = 1,
    DTI_DATA_5_MOTOR_ACCELERATION_TEMPERATURE_LIMIT_START = 38,
    DTI_DATA_5_MOTOR_ACCELERATION_TEMPERATURE_LIMIT_LEN   = 1,
    DTI_DATA_5_MOTOR_TEMPERATURE_LIMIT_START = 39,
    DTI_DATA_5_MOTOR_TEMPERATURE_LIMIT_LEN   = 1,
    DTI_DATA_5_RPM_MIN_LIMIT_START = 40,
    DTI_DATA_5_RPM_MIN_LIMIT_LEN   = 1,
    DTI_DATA_5_RPM_MAX_LIMIT_START = 41,
    DTI_DATA_5_RPM_MAX_LIMIT_LEN   = 1,
    DTI_DATA_5_POWER_LIMIT_START = 42,
    DTI_DATA_5_POWER_LIMIT_LEN   = 1,
    DTI_DATA_5_RESERVED_START = 43,
    DTI_DATA_5_RESERVED_LEN   = 1,
    DTI_DATA_5_RESERVED_START = 48,
    DTI_DATA_5_RESERVED_LEN   = 1,
    DTI_DATA_5_CAN_VERSION_START = 56,
    DTI_DATA_5_CAN_VERSION_LEN   = 1,
} DTI_DATA_5_SIGNALS_t;

// Signals for EM Measurement
typedef enum {
    EM_MEASUREMENT_CURRENT_START = 0,
    EM_MEASUREMENT_CURRENT_LEN   = 1,
    EM_MEASUREMENT_VOLTAGE_START = 32,
    EM_MEASUREMENT_VOLTAGE_LEN   = 1,
} EM_MEASUREMENT_SIGNALS_t;

// Signals for EM Status
typedef enum {
    EM_STATUS_VIOLATION_START = 0,
    EM_STATUS_VIOLATION_LEN   = 1,
    EM_STATUS_LOGGING_START = 1,
    EM_STATUS_LOGGING_LEN   = 1,
    EM_STATUS_ENERGY_START = 8,
    EM_STATUS_ENERGY_LEN   = 1,
} EM_STATUS_SIGNALS_t;

// Signals for EM Team Data 1
typedef enum {
    EM_TEAM_DATA_1_TEAM_SIGNAL_1_START = 0,
    EM_TEAM_DATA_1_TEAM_SIGNAL_1_LEN   = 1,
    EM_TEAM_DATA_1_TEAM_SIGNAL_2_START = 32,
    EM_TEAM_DATA_1_TEAM_SIGNAL_2_LEN   = 1,
} EM_TEAM_DATA_1_SIGNALS_t;

// Signals for EM Team Data 2
typedef enum {
    EM_TEAM_DATA_2_TEAM_SIGNAL_3_START = 0,
    EM_TEAM_DATA_2_TEAM_SIGNAL_3_LEN   = 1,
    EM_TEAM_DATA_2_TEAM_SIGNAL_4_START = 32,
    EM_TEAM_DATA_2_TEAM_SIGNAL_4_LEN   = 1,
} EM_TEAM_DATA_2_SIGNALS_t;

// Signals for EM Temperature
typedef enum {
    EM_TEMPERATURE_MUX_SIGNAL_START = 0-2,
    EM_TEMPERATURE_MUX_SIGNAL_LEN   = 1,
    EM_TEMPERATURE_NUM_SENSORS_START = 3-7,
    EM_TEMPERATURE_NUM_SENSORS_LEN   = 1,
    EM_TEMPERATURE_MIN_TEMP_START = 8,
    EM_TEMPERATURE_MIN_TEMP_LEN   = 1,
    EM_TEMPERATURE_MAX_TEMP_START = 16,
    EM_TEMPERATURE_MAX_TEMP_LEN   = 1,
    EM_TEMPERATURE_TEMP_5N_START = 24,
    EM_TEMPERATURE_TEMP_5N_LEN   = 1,
    EM_TEMPERATURE_TEMP_5N_1_START = 32,
    EM_TEMPERATURE_TEMP_5N_1_LEN   = 1,
    EM_TEMPERATURE_TEMP_5N_2_START = 40,
    EM_TEMPERATURE_TEMP_5N_2_LEN   = 1,
    EM_TEMPERATURE_TEMP_5N_3_START = 48,
    EM_TEMPERATURE_TEMP_5N_3_LEN   = 1,
    EM_TEMPERATURE_TEMP_5N_4_START = 56,
    EM_TEMPERATURE_TEMP_5N_4_LEN   = 1,
} EM_TEMPERATURE_SIGNALS_t;

// Signals for IMD general
typedef enum {
    IMD_GENERAL_R_ISO_CORRECTED_START = 0,
    IMD_GENERAL_R_ISO_CORRECTED_LEN   = 1,
    IMD_GENERAL_R_ISO_STATUS_START = 16,
    IMD_GENERAL_R_ISO_STATUS_LEN   = 1,
    IMD_GENERAL_ISO_MEAS_COUNT_START = 24,
    IMD_GENERAL_ISO_MEAS_COUNT_LEN   = 1,
    IMD_GENERAL_STATUS_START = 32,
    IMD_GENERAL_STATUS_LEN   = 1,
    IMD_GENERAL_ACTIVITY_START = 48,
    IMD_GENERAL_ACTIVITY_LEN   = 1,
    IMD_GENERAL_RESERVED_START = 56,
    IMD_GENERAL_RESERVED_LEN   = 1,
} IMD_GENERAL_SIGNALS_t;

#endif // CUSTOM_CAN_ID_H
