add_library(PERIPHERAL_TIMEDCAN_LIB INTERFACE)

target_include_directories(
	PERIPHERAL_TIMEDCAN_LIB
	INTERFACE
		${CMAKE_CURRENT_LIST_DIR}/Inc
)

target_sources(
	PERIPHERAL_TIMEDCAN_LIB
	INTERFACE
		${CMAKE_CURRENT_LIST_DIR}/Src/can.c
)

set_target_properties(
	PERIPHERAL_TIMEDCAN_LIB
	PROPERTIES
		DEPRECATION
			"PERIPHERAL_TIMEDCAN_LIB is deprecated and should be replaced by CUBE_CAN_LIB."
)
