name: Autogen
run-name: Autogen - ${{ github.ref_name }}

on:
  pull_request:
    paths:
      - "Autogen/**"
      - ".github/workflows/Autogen.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  canfigurator:
    name: CANfigurator
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Pull Request
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.AUTOFORMAT_COMMIT_TOKEN }}

      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@a198315ec4e9244f206879ea7b63078003aec8a6 # v1.41.1
        with:
          install-modules: |
            Readonly
            YAML::XS

      - name: Run CAN Parser
        run: |
          set -o pipefail
          echo "<details open><summary>CAN Parser Output</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          make -C Autogen/CAN all 2>&1 | tee -a $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: Auto Format Header Files
        run: |
          set -o pipefail
          echo "<details open><summary>Clang-Format Output</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          clang-format -i --verbose Autogen/CAN/Inc/*.h 2>&1 | tee -a $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: Save Changes
        uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10.0.0
        if: github.ref_type != 'tag'
        env:
          HOME: ${{ github.workspace }}
        with:
          default_author: github_actions
          message: "Automatic CANfigurator: Updated CAN files automatically"
          fetch: "false"
          add: "--force Autogen/CAN/Inc/*.h Autogen/CAN/Doc/*.dbc"
