name: Autogen
run-name: Autogen - ${{ github.ref_name }}

on:
  pull_request:
    paths:
      - "Autogen/**"
      - ".github/workflows/Autogen.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  canfigurator:
    name: CANfigurator
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Acquire Secrets
        uses: Gaucho-Racing/vault-pull-secrets@fa8269ea0faa78bd55f8628fd13680dae68908a2 # v1.3.0
        with:
          secrets: firmware-monorepo-autoformat.github_pat

      - name: Checkout Pull Request
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ env.GITHUB_PAT }}

      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@53e33bb27be492a926eee378e8a5f7ff6618b061 # v1.43.1
        with:
          install-modules: |
            Readonly
            YAML::XS

      - name: Run CAN Parser
        run: |
          set -o pipefail
          echo "<details open><summary>CAN Parser Output</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          make -C Autogen/CAN all 2>&1 | tee -a $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: Auto Format Header Files
        run: |
          set -o pipefail
          echo "<details open><summary>Clang-Format Output</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          clang-format -i --verbose Autogen/CAN/Inc/*.h 2>&1 | tee -a $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: Save Changes
        uses: EndBug/add-and-commit@cc9c08ba6c8df3b93a8f2db63e89b98368ae2ae8 # v11.1.1
        if: github.ref_type != 'tag'
        env:
          HOME: ${{ github.workspace }}
        with:
          default_author: github_actions
          message: "Automatic CANfigurator: Updated CAN files automatically"
          fetch: "false"
          add: "--force Autogen/CAN/Inc/*.h Autogen/CAN/Doc/*.dbc"
