name: Autogen
run-name: Autogen - ${{ github.ref_name }}

on:
  pull_request:
    paths:
      - 'Autogen/**'
      - '.github/workflows/Autogen.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  canfigurator:
    name: CANfigurator
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Checkout Pull Request
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.AUTOFORMAT_COMMIT_TOKEN }}

      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@9f8c263975569ff3b4e510cb1f8813115749e146  # v1.41.0
        with:
          install-modules: |
            Readonly
            YAML::XS

      - name: Run CAN Parser
        run: |
          set -o pipefail
          echo "<details open><summary>CAN Parser Output</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          make -C Autogen/CAN all 2>&1 | tee -a $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: Auto Format Header Files
        run: |
          set -o pipefail
          echo "<details open><summary>Clang-Format Output</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          clang-format -i --verbose Autogen/CAN/Inc/*.h 2>&1 | tee -a $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: Save Changes
        uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321  # v10.0.0
        if: github.ref_type != 'tag'
        env:
          HOME: ${{ github.workspace }}
        with:
          default_author: github_actions
          message: 'Automatic CANfigurator: Updated CAN files automatically'
          fetch: 'false'
          add: '--force Autogen/CAN/Inc/*.h Autogen/CAN/Doc/*.dbc'
