name: CMake
run-name: CMake Build All Presets - ${{ github.ref_name }}

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cmake:
    name: Configure and Build
    runs-on: ${{ matrix.operatingSystem }}
    permissions:
      contents: read
    strategy:
      fail-fast: true
      matrix:
        prefix: [ "Debug", "Release", "MinSizeRel", "RelWithDebInfo" ]
        operatingSystem: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Arm Toolchain (Ubuntu)
        if: matrix.operatingSystem == 'ubuntu-latest'
        shell: bash
        run: |
          echo "set man-db/auto-update false" | sudo debconf-communicate
          sudo rm /var/lib/man-db/auto-update
          set -o pipefail
          echo "<details><summary>Install Arm Toolchain</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          sudo apt-get install gcc-arm-none-eabi --no-install-suggests 2>&1 | tee -a $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: Install Arm Toolchain (macOS)
        if: matrix.operatingSystem == 'macos-latest'
        shell: bash
        run: |
          set -o pipefail
          echo "<details><summary>Install Arm Toolchain</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          brew install --cask gcc-arm-embedded 2>&1 | tee -a $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: Install Arm Toolchain (Windows)
        if: matrix.operatingSystem == 'windows-latest'
        shell: bash
        run: |
          set -o pipefail
          echo "<details><summary>Install Arm Toolchain</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          choco install -y arm-none-eabi-gcc 2>&1 | tee -a $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: CMake Configuration
        shell: bash
        run: |
          set -o pipefail
          echo "<details><summary>CMake Configuration</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cmake --preset ${{ matrix.prefix }} 2>&1 | tee -a $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: CMake Build
        shell: bash
        run: |
          set -o pipefail
          echo "<details><summary>CMake Build</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cmake --build build/${{ matrix.prefix }} 2>&1 | tee -a $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: Executable Size
        shell: bash
        run: |
          set -o pipefail
          echo "<details open><summary>Executable Size</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          arm-none-eabi-size build/${{ matrix.prefix }}/*.elf 2>&1 | tee -a $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: Upload RelWithDebInfo Builds
        if: matrix.prefix == 'RelWithDebInfo' && matrix.operatingSystem == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: firmware-release-with-debug-info
          path: build/${{ matrix.prefix }}/*.elf
          retention-days: 7
          if-no-files-found: error
          compression-level: 0
          overwrite: true
