name: Autogen
run-name: Autogen - ${{ github.ref_name }}

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  canfigurator:
    name: CANfigurator Setup
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Checkout Pull Request
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.AUTOFORMAT_COMMIT_TOKEN }}

      - name: Install YAML::XS
        uses: perl-actions/install-with-cpanm@v1
        with:
          install: YAML::XS

      - name: Run Parsers
        run: |
            perl Autogen/CAN/Src/CANdlerparser.pl Autogen/CAN/Doc/format.CANdo
            perl Autogen/CAN/Src/CANparser.pl Autogen/CAN/Doc/format.CANdo
            # perl Autogen/CAN/Src/DBC.pl Autogen/CAN/Doc/format.CANdo
            perl Autogen/CAN/Src/GRparser.pl Autogen/CAN/Doc/format.CANdo
            perl Autogen/CAN/Src/MSGparser.pl Autogen/CAN/Doc/format.CANdo

      - name: Clang-Format Autogen Files
        run: |
          set -o pipefail
          git ls-files 'Autogen/CAN/*.c' 'Autogen/CAN/*.h' | xargs -r clang-format -i --verbose

      - name: Save Changes
        uses: EndBug/add-and-commit@v9
        if: github.ref_type != 'tag'
        env:
          HOME: ${{ github.workspace }}
        with:
          default_author: github_actions
          message: 'Automatic CANfigurator: Updated CAN files automatically'
          fetch: 'false'
          add: '. --force'
