name: Autogen
run-name: Autogen - ${{ github.ref_name }}

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  canfigurator:
    name: CANfigurator Setup
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Checkout Pull Request
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.AUTOFORMAT_COMMIT_TOKEN }}

      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@b6cfc127f1b0a63ac98797800f641494d80f42f8  # v1.37.1
        with:
          install-modules: 'YAML::XS'

      - name: Run Parsers
        run: |
            perl Autogen/CAN/Src/STRUCTparser.pl Autogen/CAN/Doc/format.CANdo Autogen/CAN/Inc/Struct_ID.h
            perl Autogen/CAN/Src/CANparser.pl Autogen/CAN/Doc/format.CANdo Autogen/CAN/Inc/Custom_CAN_ID.h
            perl Autogen/CAN/Src/DBCparser.pl Autogen/CAN/Doc/format.CANdo Autogen/CAN/Doc/output.dbc
            perl Autogen/CAN/Src/GRparser.pl Autogen/CAN/Doc/format.CANdo Autogen/CAN/Inc/GR_IDS.h
            perl Autogen/CAN/Src/MSGparser.pl Autogen/CAN/Doc/format.CANdo Autogen/CAN/Inc/CAN_msg_ID.h
      - name: Auto Format header files
        run: |
            clang-format -i --verbose Autogen/CAN/Inc/*.h
            # clang-format -i --verbose Autogen/CAN/Inc/Custom_CAN_ID.h
            # clang-format -i --verbose Autogen/CAN/Inc/GR_IDS.h
            # clang-format -i --verbose Autogen/CAN/Inc/CAN_msg_ID.h
      # - name: Clang-Format Autogen Files
      #   run: |
      #     set -o pipefail
      #     git ls-files 'Autogen/CAN/*.c' 'Autogen/CAN/*.h' | xargs -r clang-format -i --verbose

      - name: Save Changes
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5  # v9.1.4
        if: github.ref_type != 'tag'
        env:
          HOME: ${{ github.workspace }}
        with:
          default_author: github_actions
          message: 'Automatic CANfigurator: Updated&Formatted CAN files automatically'
          fetch: 'false'
          add: '. --force'

      # - name: FAIL JOB
      #   run: exit 1
