name: clang-tidy

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Install Arm Toolchain
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '12.2.Rel1'

    - name: Run clang-tidy
      run: |
        clang-tidy -p build $(git diff --name-only origin/${{ github.base_ref }} | grep '\.cpp$') || exit 1
