name: clang-tidy

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy cmake ninja-build

    - name: Configure
      run: |
          cmake -S . -B build \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -G Ninja
            
    - uses: ZedThree/clang-tidy-review@v0.22.0
      id: review
      with:
          build_dir: build

    - uses: ZedThree/clang-tidy-review/upload@v0.22.0

    - if: steps.review.outputs.total_comments > 0
      run: exit 1
