name: clang-tidy

on: [pull_request]

permissions:
  contents: read

jobs:
  tidy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Install Arm Toolchain
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '12.2.Rel1'

    - name: Configure
      run: cmake --preset Debug

    - name: Run clang-tidy
      run: 
        clang-tidy -p build/Debug $files
