name: Valgrind
run-name: Valgrind HOOTL Tests - ${{ github.ref_name }}

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  ctest:
    name: Run Valgrind on HOOTLTest
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Valgrind
        run: |
          echo "set man-db/auto-update false" | sudo debconf-communicate
          sudo rm /var/lib/man-db/auto-update
          sudo apt-get install -y valgrind --no-install-suggests --no-install-recommends

      - name: Build HOOTLTest
        run: |
          set -o pipefail
          echo "<details><summary>Make HOOTLTest</summary>" >> $GITHUB_STEP_SUMMARY
          make HOOTLTest 2>&1 | tee -a $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: Run Tests
        run: |
          set -o pipefail
          echo "<details><summary>Run HOOTLTest</summary>" >> $GITHUB_STEP_SUMMARY
          make test 2>&1 | tee -a $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: Run Memory Check
        run: |
          set -o pipefail
          echo "<details><summary>HOOTLTest Memory Check</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          make memory_check 2>&1 | tee -a $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
