name: Valgrind
run-name: Valgrind HOOTL Tests - ${{ github.ref_name }}

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  ctest:
    name: Complete Memory Check on HOOTLTest
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Set up Valgrind
        uses: awalsh128/cache-apt-pkgs-action@v1.6.0
        with:
          packages: valgrind

      - name: Build and Run Memory Check
        run: |
          set -o pipefail
          echo "<details open><summary>HOOTLTest Memory Check</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          make valgrind 2>&1 | tee -a $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
