name: Perl Critic
run-name: Perl Critic Linting - ${{ github.ref_name }}

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  perlcritic:
    name: Lint Perl
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Install Perl Critic
        uses: perl-actions/install-with-cpanm@v1
        with:
          install: 'Perl::Critic'

      - name: Run Perl Critic
        run: |
          set -o pipefail
          echo "<details open><summary>Perl::Critic Output</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          perlcritic . | tee -a $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
